// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCredentialStoreMock creates a new instance of CredentialStoreMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialStoreMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialStoreMock {
	mock := &CredentialStoreMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CredentialStoreMock is an autogenerated mock type for the CredentialStore type
type CredentialStoreMock struct {
	mock.Mock
}

type CredentialStoreMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CredentialStoreMock) EXPECT() *CredentialStoreMock_Expecter {
	return &CredentialStoreMock_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type CredentialStoreMock
func (_mock *CredentialStoreMock) Clear() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CredentialStoreMock_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type CredentialStoreMock_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *CredentialStoreMock_Expecter) Clear() *CredentialStoreMock_Clear_Call {
	return &CredentialStoreMock_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *CredentialStoreMock_Clear_Call) Run(run func()) *CredentialStoreMock_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CredentialStoreMock_Clear_Call) Return(err error) *CredentialStoreMock_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CredentialStoreMock_Clear_Call) RunAndReturn(run func() error) *CredentialStoreMock_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type CredentialStoreMock
func (_mock *CredentialStoreMock) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CredentialStoreMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type CredentialStoreMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *CredentialStoreMock_Expecter) Close() *CredentialStoreMock_Close_Call {
	return &CredentialStoreMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *CredentialStoreMock_Close_Call) Run(run func()) *CredentialStoreMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CredentialStoreMock_Close_Call) Return(err error) *CredentialStoreMock_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CredentialStoreMock_Close_Call) RunAndReturn(run func() error) *CredentialStoreMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAPIKeyCredential provides a mock function for the type CredentialStoreMock
func (_mock *CredentialStoreMock) SaveAPIKeyCredential(apiKey string, tenantDomain string) error {
	ret := _mock.Called(apiKey, tenantDomain)

	if len(ret) == 0 {
		panic("no return value specified for SaveAPIKeyCredential")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(apiKey, tenantDomain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CredentialStoreMock_SaveAPIKeyCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAPIKeyCredential'
type CredentialStoreMock_SaveAPIKeyCredential_Call struct {
	*mock.Call
}

// SaveAPIKeyCredential is a helper method to define mock.On call
//   - apiKey string
//   - tenantDomain string
func (_e *CredentialStoreMock_Expecter) SaveAPIKeyCredential(apiKey interface{}, tenantDomain interface{}) *CredentialStoreMock_SaveAPIKeyCredential_Call {
	return &CredentialStoreMock_SaveAPIKeyCredential_Call{Call: _e.mock.On("SaveAPIKeyCredential", apiKey, tenantDomain)}
}

func (_c *CredentialStoreMock_SaveAPIKeyCredential_Call) Run(run func(apiKey string, tenantDomain string)) *CredentialStoreMock_SaveAPIKeyCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CredentialStoreMock_SaveAPIKeyCredential_Call) Return(err error) *CredentialStoreMock_SaveAPIKeyCredential_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CredentialStoreMock_SaveAPIKeyCredential_Call) RunAndReturn(run func(apiKey string, tenantDomain string) error) *CredentialStoreMock_SaveAPIKeyCredential_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTokenCredential provides a mock function for the type CredentialStoreMock
func (_mock *CredentialStoreMock) SaveTokenCredential(token string, refreshToken string, tenantDomain string) error {
	ret := _mock.Called(token, refreshToken, tenantDomain)

	if len(ret) == 0 {
		panic("no return value specified for SaveTokenCredential")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(token, refreshToken, tenantDomain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CredentialStoreMock_SaveTokenCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTokenCredential'
type CredentialStoreMock_SaveTokenCredential_Call struct {
	*mock.Call
}

// SaveTokenCredential is a helper method to define mock.On call
//   - token string
//   - refreshToken string
//   - tenantDomain string
func (_e *CredentialStoreMock_Expecter) SaveTokenCredential(token interface{}, refreshToken interface{}, tenantDomain interface{}) *CredentialStoreMock_SaveTokenCredential_Call {
	return &CredentialStoreMock_SaveTokenCredential_Call{Call: _e.mock.On("SaveTokenCredential", token, refreshToken, tenantDomain)}
}

func (_c *CredentialStoreMock_SaveTokenCredential_Call) Run(run func(token string, refreshToken string, tenantDomain string)) *CredentialStoreMock_SaveTokenCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CredentialStoreMock_SaveTokenCredential_Call) Return(err error) *CredentialStoreMock_SaveTokenCredential_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CredentialStoreMock_SaveTokenCredential_Call) RunAndReturn(run func(token string, refreshToken string, tenantDomain string) error) *CredentialStoreMock_SaveTokenCredential_Call {
	_c.Call.Return(run)
	return _c
}
