version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/safedep
    binary: safedep
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/safedep/cli/internal/version.Version={{ .Version }} -X github.com/safedep/cli/internal/version.Commit={{ .FullCommit }}
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

universal_binaries:
  - replace: true

brews:
  - name: cli
    homepage: https://github.com/safedep/cli
    description: "The SafeDep Platform CLI"
    license: "Apache-2.0"
    repository:
      owner: safedep
      name: homebrew-tap
      branch: main
